### ISSUE TITLE
Pairing procedure

### ISSUE THREAD

**Issue by DudnykOleksandr** [grill2010/RemotePlayPrototype#9]
Hey, man!
How hard is it to implement a pairing with a console without code and account id, just like the original Sony client does, just using username-password?

**Comment by grill2010** [comment]
If you mean pairing without the need of entering the 8 digit pin then it's probably not much effort to implement BUT this has to be reverse engineered which is much effort. As far as I know this is handled via PSN and through some other Sony servers. I'm interested in this as well but I don't have any plans yet to do something in this direction. If you find something out please let me know.

**Comment by DudnykOleksandr** [comment]
Yep that is exactly what I meant, thanks

**Comment by LuckyD0e001** [comment]
hey bro help me pls, I wanted the project for ps4 remote play from windows that to open in vb.net I really want to study! Please help me

**Comment by DudnykOleksandr** [comment]
Hey man, 
1. it is outdated
2. it is written in C#
Sorry, what is your intention?

**Comment by grill2010** [comment]
@DudnykOleksandr @LuckyD0e001 
Literally the first sentence of the README

**### Quick and dirty prototype to play around with the protocol. This is just a research project there is no support. If there are some enthusiastic reverse engineers out there it would be great if they could contribute to the project.**

The intention was to provide some insights of how the Remote Play protocol works, yes it is outdated now and no I don't have any plans to update this project soon. I used it this quick and dirty project to build PSPlay and to for testing things out. If you want a working solution check out [Chiaki](https://git.sr.ht/~thestr4ng3r/chiaki)

**Comment by grill2010** [comment]
@DudnykOleksandr what is your intention?

**Comment by LuckyD0e001** [comment]
but the chiaki project is only for android i wanted for pc
:/

**Comment by LuckyD0e001** [comment]
do you have discord

**Comment by DudnykOleksandr** [comment]
> do you have discord

it is available for Windows also see Chiaki-v1.3.0-Windows-x86_64.zip
https://github.com/thestr4ng3r/chiaki/releases/tag/v1.3.0

Closing this issue...
